services:
  moodle:
    build: .
    container_name: moodle
    ports:
      - "80:80"  
    volumes:
      - moodledata:/var/moodledata  
      - moodle_data:/var/www/html/moodle  
    environment:
      - MOODLE_DATABASE_HOST=moodle_db
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_DATABASE_USER=moodle_user
      - MOODLE_DATABASE_PASSWORD=moodle_password
    depends_on:
      - moodle_db

  moodle_db:
    image: mariadb:10.6
    container_name: moodle_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle_user
      - MYSQL_PASSWORD=moodle_password
    volumes:
      - moodle_db_data:/var/lib/mysql  

volumes:
  moodle_data:  
  moodledata:  
  moodle_db_data: 
